### ISSUE TITLE
Do not use rm -rf when there is no need

### ISSUE THREAD

**Issue by andreas--e** [tyoyo/zippyshare#3]
(enhancement suggestion) 
`-r` is RECURSIVE. However, as you only want to remove (cookie|info.txt) in current directory, the `-r` can be omitted. Though it might not do any mischief in your case, you had better omit it. :)

I will give an example (DANGER AHEAD) 
```bash
if [ -f "$1" ]; then
   rm -rf $1
fi
```

"If file specified as first argument exists, DELETE IT"

Now imagine someone makes a cut-and-paste mistake and calls your script instead of 
`zippyshare.sh http://someurl.xyz/...`
by
`zippyshare.sh music1`

This will RECURSIVELY delete everything called "music1". So if there is a directory in there with the same name, it will be emptied. Very, very dangerous.

This says:

**Comment by tyoyo** [comment]
if [ -f "$1" ] - just check for regular file existence not a directory, if music1 is a directory, rm -rf $1 will skip.
-r deleted for security. :）

**Comment by andreas--e** [comment]
Dang, you're right. I forgot that despite in *nix systems, everything is a file (internally), the `bash` built-in `test` command (or `[ ]`) does distinguish between folders `-d` and files `-f`. My bad.
