### ISSUE TITLE
script will only work for rar files :)

### ISSUE THREAD

**Issue by andreas--e** [tyoyo/zippyshare#4]
`algorithm=$(cat info.txt | grep -E "dlbutton(.*)\/d\/(.*)rar" | head -n 1 | cut -d'/' -f4 | cut -d'(' -f2 | cut -d')' -f1)`

(note backticks are not only old-fashioned (use `$()` instead) but as you can see here, will break Markdown as well, that's why I had to rewrite it)

Can you tell me how this is supposed to work with a .zip file? Or what if a Korean user comes along with their .alz files? ;) Wouldn't even work for `.mp3` mixes that are usually not archived, but left as-is.
Looks hardcoded to me with `.rar` ... this should **never** be done.

**Comment by tyoyo** [comment]
Deleted rar from regular expression "dlbutton(._)\/d\/(._)rar".
